name: Unity Build

on:
  push:
    branches: [ "main" ] # Burayı "main" olarak değiştirdik

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          projectPath: BasitOynatici
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} # Bu satır çok önemli
